SessionManagement/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SessionManagement.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

SessionManagement/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SessionManagement.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    public const string SKeyName="_Name";
    public const string SKeyAge="_Age";
    public const string SKeyTime="_Time";
    [BindProperty]
    public Customer Customer{get;set;}

    [BindProperty]
    public int Amount{get;set;}
    [TempData]
    public string TempMessage{get;set;}

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public IActionResult OnPostSubmitForm()
    {
        if(HttpContext.Session.GetString(SKeyAge)==null || HttpContext.Session.GetString(SKeyAge)==""){
            HttpContext.Session.SetString(SKeyName,"Session One");
            // HttpContext.Session.SetString(SKeyName,"Session Two");
            HttpContext.Session.SetInt32(SKeyAge,20);
        }

        if (HttpContext.Session.Get(SKeyTime) == default)
            {
                HttpContext.Session.SetString(SKeyTime, DateTime.Now.ToString());
            }

        var name=HttpContext.Session.GetString(SKeyName);
        var age=HttpContext.Session.GetInt32(SKeyAge);
        var time=HttpContext.Session.GetString(SKeyTime);

        _logger.LogInformation($"Session Name : {name}", name);
        _logger.LogInformation($"Session Age : {age}", age);
        _logger.LogInformation($"Session Time : {time}", time);
        _logger.LogInformation($"Amount(Rs.) : {Amount}");
        TempMessage=$"{Customer.Id} => {Customer.Name}";

        return RedirectToPage();
    }
  
}

public class Customer{
    public int Id{get;set;}
    
    public string? Name{get;set;}
}

SessionManagement/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SessionManagement.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

SessionManagement/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to</h1>
    <form method="post" asp-page-handler="SubmitForm">
        <h1 class="display-4"><b>Session Management</b></h1>

        <div>
        <label asp-for="Customer.Id"></label>
        <input asp-for="Customer.Id"  />
        </div>
<br>
        <div>
        <label asp-for="Customer.Name"></label>
        <input asp-for="Customer.Name"  />
        </div>
<br>
        <div>
        <label asp-for="Amount"></label>
        <input asp-for="Amount"/>
        </div>

        <button type="submit" id="btn">Submit</button>
    </form>

    @if(!string.IsNullOrEmpty(@Model.TempMessage)){
        <div>
            @Model.TempMessage
        </div>
    }
</div>

SessionManagement/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SessionManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SessionManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SessionManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SessionManagement - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>